dist: trusty

sudo: false

language:
  - php

os:
  - linux

php:
  - nightly
  - 7.2
  - 7.1
  - 5.6
  - 5.4

matrix:
  allow_failures:
    - php: nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION == "5.4" ]]; then composer require 'phpunit/phpunit=4.8.x'; composer install; fi
  - if [[ $TRAVIS_PHP_VERSION == "5.6" ]]; then composer require 'phpunit/phpunit=5.7.x'; composer install; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" || $TRAVIS_PHP_VERSION == "nightly" ]]; then composer require 'phpunit/phpunit=6.5.x'; composer install; fi

script:
  - ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php --configuration ./test/phpunit.xml ./test/FMDataAPIUnitTest.php

notifications:
  slack:
    rooms:
      - intermediator:INKkFZQWI94gsq6DYxRnaWeb#product
    on_success: change
    on_failure: always
    on_start: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ab3046b24c1b21df358d
